const menu = [
  {
    id: 1,
    title: 'meat free meals',
    category: 'healthy',
    //price: 
    img: './images/item-1.jpeg',
    desc: `Great for vegerarians, filiing and ever so fresh `,
  },
  {
    id: 2,
    title: 'Healthy Light Meal',
    category: 'healthy',
    //price: 13.99,
    img: './images/item-2.jpeg',
    desc: `An assortment of tangy salads garnished with great exotic spices mouth watering sauces`,
  },
  {
    id: 3,
    title: 'Meaty Platter',
    category: 'platters',
    //price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Platters for all occassions, with wraps, meatballs, samoosas and an assortment of vegetables `,
  },
  {
    id: 4,
    title: 'Platters for all occasions',
    category: 'platters',
    //price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Tantalizing platters of all sizes, tailor made for any occassion `,
  },
  {
    id: 5,
    title: 'Platter For Two',
    category: 'platters',
    price: 'R'+150,
    img: './images/item-5.jpeg',
    desc: `Tantalizing platters of all sizes, tailor made for any occassion `,
  },
  {
    id: 6,
    title: 'Dumpling with Mogudu & Spinch',
    category: 'lunch',
    price: 'R'+65,
    img: './images/item-6.jpeg',
    desc: `Great local recipe that is filling, served with an assortment of veggies`,
  },
  {
    id: 7,
    title: 'Baked Treats',
    category: 'baked',
    //price: 8.99,
    img: './images/item-7.jpeg',
    desc: `Filling rolls and breads served hot, great for school lunch boxes`,
  },
  {
    id: 8,
    title: 'Cinamon Rolls',
    category: 'baked',
    price: 'R'+10,
    img: './images/item-10.jpeg',
    desc: `Filling rolls and breads served hot, great for desserts, teas and snacking`,
  },
  {
    id: 9,
    title: 'Vetkoer/AmaGwinya',
    category: 'baked',
    price: 'R'+10,
    img: './images/item-13.jpg',
    desc: `Freshly made with minimal oil, tasty and ready to carry you for the day`,
  },

  {
    id: 10,
    title: 'Desserts',
    category: 'baked',
    price: 'R'+10,
    img: './images/item-11.jpg',
    desc: `Mouthwatering desserts ranging from different cakes, cake slices , mousses etc`,
  },

  {
    id: 11,
    title: 'Grilled Chicken',
    category: 'lunch',
    //price: 12.99,
    img: './images/item-8.jpeg',
    desc: `Great drumsticks and wings grilled to perfection `,
  },
  {
    id: 12,
    title: 'Dumpling with beef and pumpkin',
    category: 'lunch',
    //price: 16.99,
    img: './images/item-9.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
